"$schema" = "./node_modules/wrangler/config-schema.json"

name = "homepage"
compatibility_date = "2026-02-19"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true
workers_dev = false

[[routes]]
pattern = "vait.au"
custom_domain = true

[assets]
directory = "dist"
not_found_handling = "single-page-application"

[observability]
enabled = true
head_sampling_rate = 1
persist = true

[observability.logs]
invocation_logs = true

[build]
command = "pnpm run ci && pnpm run test && pnpm run tyepcheck && pnpm run build:cf"
