#:schema node_modules/wrangler/config-schema.json

name = "homepage"
compatibility_date = "2026-02-19"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "dist"
not_found_handling = "single-page-application"
