#:schema node_modules/wrangler/config-schema.json

name = "vait-homepage-worker"
compatibility_date = "2025-09-15"
compatibility_flags = ["nodejs_compat"]

[assets]
not_found_handling = "single-page-application"
